"""Mate birthdate mandatory

Revision ID: 04a8d68649e9
Revises: 175b50fdc725
Create Date: 2025-12-06 15:48:58.389612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04a8d68649e9'
down_revision: Union[str, Sequence[str], None] = '175b50fdc725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth',
                   existing_type=sa.DATE(),
                   nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth',
                   existing_type=sa.DATE(),
                   nullable=True)
    # ### end Alembic commands ###
