"""Remove username and add birthdate

Revision ID: 175b50fdc725
Revises: d0d5d7e87b17
Create Date: 2025-12-06 15:45:02.543895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '175b50fdc725'
down_revision: Union[str, Sequence[str], None] = 'd0d5d7e87b17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), nullable=False))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=1)
    op.drop_column('users', 'date_of_birth')
    # ### end Alembic commands ###
